# Generated by Django 5.2.15 on 2026-06-09 22:36

import apps.core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=64)),
                ('encrypted_payload', apps.core.models.EncryptedJSONField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
