# Generated by Django 5.2.15 on 2026-06-09 22:36

import apps.core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('ciphertext_size', models.PositiveBigIntegerField()),
                ('ciphertext_sha256', models.BinaryField()),
                ('encrypted_metadata', apps.core.models.EncryptedJSONField()),
                ('upload_state', models.CharField(choices=[('initiated', 'Initiated'), ('uploaded', 'Uploaded'), ('complete', 'Complete'), ('aborted', 'Aborted'), ('deleted', 'Deleted')], default='initiated', max_length=32)),
                ('upload_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('size_bucket', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TenantStorageUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciphertext_bytes_used', models.PositiveBigIntegerField(default=0)),
                ('attachments_count', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
