# Generated by Django 5.2.15 on 2026-06-09 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='tenantstorageusage',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage', to='tenants.organization'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['tenant', 'note'], name='attachments_tenant__ecad53_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['tenant', 'upload_state'], name='attachments_tenant__e731ae_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['upload_expires_at'], name='attachments_upload__b3c379_idx'),
        ),
    ]
