# Generated by Django 5.2.15 on 2026-06-09 22:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=32)),
                ('provider_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('signature_valid', models.BooleanField(default=False)),
                ('processing_status', models.CharField(default='received', max_length=32)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
