# Generated by Django 5.2.15 on 2026-06-09 22:36

import apps.core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kdf_algorithm', models.CharField(default='argon2id', max_length=32)),
                ('kdf_params', models.JSONField()),
                ('password_salt', models.BinaryField()),
                ('public_encryption_key', models.BinaryField()),
                ('public_signing_key', models.BinaryField()),
                ('public_encryption_key_fingerprint', models.CharField(blank=True, max_length=128)),
                ('public_signing_key_fingerprint', models.CharField(blank=True, max_length=128)),
                ('encrypted_master_key', apps.core.models.EncryptedJSONField()),
                ('encrypted_private_encryption_key', apps.core.models.EncryptedJSONField()),
                ('encrypted_private_signing_key', apps.core.models.EncryptedJSONField()),
                ('recovery_wrapper', apps.core.models.EncryptedJSONField(blank=True, null=True)),
                ('key_version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token_hash', models.CharField(max_length=255, unique=True)),
                ('refresh_token_hash', models.CharField(max_length=255)),
                ('previous_refresh_token_hash', models.CharField(blank=True, max_length=255)),
                ('ip_hash', models.CharField(blank=True, max_length=128)),
                ('user_agent_hash', models.CharField(blank=True, max_length=128)),
                ('refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_reused_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
