# Generated by Django 5.2.15 on 2026-06-09 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='keymaterial',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_material', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='devices.device'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'revoked_at'], name='authenticat_user_id_377c37_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['device', 'revoked_at'], name='authenticat_device__796fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['refresh_token_hash'], name='authenticat_refresh_a2c09a_idx'),
        ),
    ]
