# Generated by Django 5.2.15 on 2026-06-09 22:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(default='free', max_length=32)),
                ('status', models.CharField(default='active', max_length=32)),
                ('billing_provider', models.CharField(blank=True, max_length=32)),
                ('provider_customer_id', models.CharField(blank=True, max_length=255)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
