# Generated by Django 5.2.15 on 2026-06-09 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaboration', '0003_initial'),
        ('devices', '0001_initial'),
        ('notes', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationpresence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_presence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncevent',
            name='actor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncevent',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='notes.note'),
        ),
        migrations.AddField(
            model_name='syncevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='synceventack',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_event_acks', to='devices.device'),
        ),
        migrations.AddField(
            model_name='synceventack',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acks', to='collaboration.syncevent'),
        ),
        migrations.AddField(
            model_name='synceventack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_event_acks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='collaborationpresence',
            index=models.Index(fields=['note', 'status', 'updated_at'], name='collaborati_note_id_b3647e_idx'),
        ),
        migrations.AddConstraint(
            model_name='collaborationpresence',
            constraint=models.UniqueConstraint(fields=('note', 'user', 'device'), name='unique_note_user_device_presence'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['tenant', 'created_at'], name='collaborati_tenant__647f10_idx'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['note', 'created_at'], name='collaborati_note_id_613ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='synceventack',
            index=models.Index(fields=['user', 'created_at'], name='collaborati_user_id_54a310_idx'),
        ),
        migrations.AddConstraint(
            model_name='synceventack',
            constraint=models.UniqueConstraint(fields=('event', 'user', 'device'), name='unique_event_user_device_ack'),
        ),
    ]
