# Generated by Django 5.2.15 on 2026-06-09 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_initial'),
        ('notes', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='note',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='noteconflict',
            name='actor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noteconflict',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='notes.note'),
        ),
        migrations.AddField(
            model_name='notekeygrant',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_grants', to='notes.note'),
        ),
        migrations.AddField(
            model_name='notekeygrant',
            name='recipient_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_note_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notekeygrant',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_note_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notelabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_links', to='notes.label'),
        ),
        migrations.AddField(
            model_name='notelabel',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_links', to='notes.note'),
        ),
        migrations.AddField(
            model_name='shareinvitation',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_invitations', to='notes.note'),
        ),
        migrations.AddField(
            model_name='shareinvitation',
            name='recipient_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_share_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shareinvitation',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_share_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notekeygrant',
            name='source_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grants', to='notes.shareinvitation'),
        ),
        migrations.AddField(
            model_name='synccheckpoint',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_checkpoints', to='devices.device'),
        ),
        migrations.AddField(
            model_name='synccheckpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_checkpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncoperationreceipt',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_receipts', to='devices.device'),
        ),
        migrations.AddField(
            model_name='syncoperationreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['tenant', 'updated_at'], name='notes_note_tenant__c370e7_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['tenant', 'state', 'updated_at'], name='notes_note_tenant__44e7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='noteconflict',
            index=models.Index(fields=['note', 'resolved_at', 'created_at'], name='notes_notec_note_id_a6487a_idx'),
        ),
        migrations.AddIndex(
            model_name='noteconflict',
            index=models.Index(fields=['actor_user', 'created_at'], name='notes_notec_actor_u_2d0275_idx'),
        ),
        migrations.AddConstraint(
            model_name='notelabel',
            constraint=models.UniqueConstraint(fields=('note', 'label'), name='unique_note_label'),
        ),
        migrations.AddIndex(
            model_name='shareinvitation',
            index=models.Index(fields=['recipient_user', 'status', 'created_at'], name='notes_share_recipie_54d02a_idx'),
        ),
        migrations.AddIndex(
            model_name='shareinvitation',
            index=models.Index(fields=['note', 'status'], name='notes_share_note_id_a607fd_idx'),
        ),
        migrations.AddIndex(
            model_name='notekeygrant',
            index=models.Index(fields=['note', 'recipient_user'], name='notes_notek_note_id_bf9435_idx'),
        ),
        migrations.AddIndex(
            model_name='synccheckpoint',
            index=models.Index(fields=['user', 'updated_at'], name='notes_syncc_user_id_cdbe48_idx'),
        ),
        migrations.AddConstraint(
            model_name='synccheckpoint',
            constraint=models.UniqueConstraint(fields=('user', 'device'), name='unique_user_device_sync_checkpoint'),
        ),
        migrations.AddIndex(
            model_name='syncoperationreceipt',
            index=models.Index(fields=['user', 'created_at'], name='notes_synco_user_id_2f712f_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncoperationreceipt',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_user_sync_idempotency_key'),
        ),
    ]
