# Generated by Django 5.2.15 on 2026-06-09 22:36

import apps.core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ciphertext', apps.core.models.EncryptedJSONField()),
                ('public_signing_key', models.BinaryField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('trusted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
