apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zknotes-api-ingress
spec:
  podSelector:
    matchLabels:
      app: zknotes-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
  egress:
    - {}

